config/routes.rb
Rails.application.routes.draw do
  resources :stages
  resources :tasks
  resources :roles
  resources :systems
  devise_for :users
  get 'projects/tasks_archive' => 'projects#tasks_archive'
  get 'projects/archive' => 'projects#archive'
  resources :projects

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  has_many :tasks, dependent: :destroy
  has_many :stages, dependent: :destroy
  has_and_belongs_to_many :users

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :name, :description, :start_date, :end_date, :customer, presence: true
  validate :deadline_is_possible?

  def deadline_is_possible?
    unless start_date.nil? || end_date.nil?
      if start_date > end_date
        errors.add(:start_date, 'must be before end_date')
      end
    end
  end

  attr_accessor :developers
  attr_accessor :scrum_master

  after_initialize :initialize_date, :if => :new_record?
  after_create :create_default_stages
  before_save :update_developers

  def developers_list
    developers = Array.new
    Role.find_by(name: "Developer").users.each do |d|
      if self.users.find_by_id(d.id).present?
        developers.push(d.id)
      end
    end
    developers
  end

  def scrum_master
    self.users.each do |u|
      if u.roles.find_by(name: "Scrum Master").present?
        return u.id
      end
    end
  end

  def developers_list_object
    developers = Array.new
    Role.find_by(name: "Developer").users.each do |d|
      if self.users.find_by_id(d.id).present?
        developers.push(d)
      end
    end
    developers
  end

  def update_progress
    progress = 0
    tasks_count = 0
    self.tasks.each do |t|
      progress += t.progress
      tasks_count += 1
    end
    self.progress = progress / tasks_count
    self.save
  end

  def deactivate
    self.is_active = false
    self.save
  end

  def activate
    self.is_active = true
    self.save
  end

private
  def create_default_stages
    self.stages << Stage.create(name: "To Do")
    self.stages << Stage.create(name: "Doing")
    self.stages << Stage.create(name: "Done")
  end

  def update_developers
    if  developers.present? then
      developers.pop() # Fix-me, I am needed because the  developers array came with a empty element.

      current_developers = developers_list

      # Removes the developers that are not in the project anymore
      (current_developers - developers).each do |d|
        self.users.delete(d)
      end

      # Adds the new developers
      (developers - current_developers).each do |d|
        self.users << User.find(d)
      end
    end
  end

  def initialize_date
    self.start_date = Time.now
    self.end_date = Time.now + 1.week
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :verify_command, only: :show

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(is_active: true)
  end

  def archive
    @projects = Project.where(is_active: false)
  end

  def tasks_archive
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks.where(is_active: false)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Verify if the user wants to deactivate or activate a project
    def verify_command
      if params[:command].present?
        if params[:command] == 'deactivate'
          deactivate
        elsif params[:command] == 'activate'
          activate
        end
      end
    end

    def activate
      Project.find(params[:id]).activate

      respond_to do |format|
        format.html { redirect_to projects_path, notice: 'O projeto foi desarquivado com sucesso.' }
        format.json { head :no_content }
      end
    end

    def deactivate
      Project.find(params[:id]).deactivate

      respond_to do |format|
        format.html { redirect_to :back, notice: 'O projeto foi arquivado com sucesso.' }
        format.json { head :no_content }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :start_date, :end_date, :image, :customer, :developers => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def stages project
    tasks = project.stages
  end

  def stage_name stage
    Stage.find(stage).name
  end

  def stage_tasks (project, stage)
    project.tasks.where(stage_id: stage, is_active: true)
  end

end

app/views/projects/_choose_scrum.html.erb
<%= label_tag :project, "Scrum Master", class: 'row' %>
<%= collection_radio_buttons( 'project', :scrum_master, @project.try(:developers_list_object), :id, :email, checked: @project.try(:scrum_master)) do |b| %>
  <% b.label(class: 'row choose-scrum') { b.radio_button + b.label + puts} %>
<% end %>

app/views/projects/_form.html.erb
<div id="project-edit">
  <%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description, 'Descrição' %>
      <%= f.text_area :description, class: 'materialize-textarea' %>
    </div>
    <div class="field">
      <%= f.label :customer, 'Cliente' %>
      <%= f.text_field :customer %>
    </div>
    <div class="field">
      <%= f.label :start_date, 'Data inicial' %>
      <%= f.date_field :start_date, value:  @project.start_date.strftime("%d %B, %Y"), class: 'datepicker' %>
    </div>
    <div class="field">
      <%= f.label :end_date, 'Data final' %>
      <%= f.date_field :end_date, value: @project.end_date.strftime("%d %B, %Y"), class: 'datepicker' %>
    </div>
    <div class="file-field input-field">
      <div class="btn">
        <span>Selecionar imagem</span>
        <%= f.file_field :image %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="Envie uma imagem descritiva">
      </div>
    </div>

    <div class="field" id="select-developers">
      <%= f.label "Desenvolvedores" %>
      <%= collection_check_boxes( 'project', :developers, User.all, :id, :email, checked: @project.developers_list) do |b| %>
      <br>
        <%= b.label(class: 'check_box-dev') { b.check_box + b.label } %>
      <% end %>
    </div>

    <br>
    <div class="col", id="load-scrum-chooser">
      <% render 'choose_scrum' %>
    </div>

    <div class="divider"></div>

    <div class="section row">
      <div class="col">
        <%= link_to 'Cancelar', :back, data: { confirm: 'Tem certeza que deseja cancelar?' },class: 'btn red accent-2 waves-effect waves-light' %>
      </div>
      <div class="col right">
        <%= f.button :button, class: 'btn waves-effect waves-light' do %>
          <i class="material-icons right">send</i>
          Salvar projeto
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<script>
var boxes, developers_list, i, len;

developers_list = document.getElementById('select-developers');

boxes = developers_list.getElementsByTagName('input');

i = 0;

len = boxes.length;

while (i < len) {
  if (boxes[i].type === 'checkbox') {
    boxes[i].onclick = function() {
      // $('#load-scrum-chooser').html("<%= j (render 'choose_scrum') %>");
      // $('#load-scrum-chooser').slideDown(350);
      // alert(this.value);
    };
  }
  i++;
}
</script>

app/views/projects/archive.html.erb
<h4 class="center-align">Projetos arquivados</h4>

<ul class="collection">
  <% @projects.each do |p| %>
    <li class="collection-item avatar">
      <img src="<%= p.image.url %>" alt="" class="circle">
      <span class="title"><%= p.name %></span>
      <p><%= p.description %><br>
         <div class="strong">Data inicial: </strong><%= p.start_date.strftime("%d/%m/%Y") %><br>
         <strong>Data final: </strong><%= p.end_date.strftime("%d/%m/%Y") %>
      </p>
      <%= link_to project_path(id: p.id, command: 'activate'), data: { confirm: 'Tem certeza que deseja desarquivar este projeto?' }, class: 'secondary-content' do %>
        <i class="material-icons">unarchive</i>
      <% end %>
    </li>
  <% end %>
</ul>
<div class="row">
  <div class="left col">
    <%= link_to 'Voltar', projects_path, class: 'waves-effect waves-light btn' %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container" >
  <h1>Editar projeto: <%= @project.name %></h1>

  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div class="row center-align">
  <div class="center-align">
    <h3>Projetos</h3>
  </div>
</div>
<div class="row">
<% @projects.each do |p| %>
    <div class="col s12 m12 l4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="<%=p.image.url%>">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">
            <%= p.name %>
            <i class="material-icons right small">info_outline</i>
          </span>
          <div class="progress">
            <div class="determinate" style="width: <%= p.progress %>%"></div>
          </div>
          <p>
            <%= link_to p, class: 'btn-floating btn-large waves-effect waves-light blue' do %>
              <i class="material-icons">dashboard</i>
            <% end %>
            <%= link_to edit_project_path(p), class: 'btn-floating btn-large waves-effect waves-light blue' do %>
              <i class="material-icons">mode_edit</i>
            <% end %>
            <%= link_to project_path(id: p.id, command: 'deactivate'), data: { confirm: 'Tem certeza que deseja arquivar este projeto?' }, class: 'btn-floating btn-large waves-effect waves-light red right' do %>
              <i class="material-icons">archive</i>
            <% end %>
          </p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%=p.name%><i class="material-icons right">close</i></span>
          <span>
          <%= p.description %>
          </span>
          <table>
            <thead>
              <tr>
                <th>Data inicial</th>
                <th>Data final</th>
                <th colspan="1"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= p.start_date.strftime("%d/%m/%Y") %></td>
                <td><%= p.end_date.strftime("%d/%m/%Y") %></td>
              </tr>
            </tbody>
            <thead>
              <tr>
                <th>Progresso do Projeto</th>
                <th colspan="1"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th colspan="3">
                  <div class="progress">
                    <div class="determinate" style="width: <%= p.progress %>%"></div>
                  </div>
                </th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
<% end %>
<div class="col right">
  <div class="row">
    <%= link_to new_project_path, class: 'btn-floating btn-large waves-effect waves-light green right' do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
  <div class="row">
    <%= link_to projects_archive_path, class: 'btn-floating btn-large waves-effect waves-light grey right' do %>
      <i class="material-icons">list</i>
    <% end %>
  </div>
</div>
  </div>

app/views/projects/new.html.erb
<div class="container" >
  <h1>Criar Novo Projeto</h1>

  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<h4 class="center-align"><%= @project.name %></h4>

<div class="row">
  <% stages(@project).each do |s| %>
    <div class="col s12 m4">
      <div class="card-panel teal">
        <span class="card-title white-text center-align">
            <h5 class="row"><%= s.name %></h5>
        </span>
          <ul class="collapsible popout" data-collapsible="expandable">
            <% stage_tasks(@project, s).each do |t| %>
                <li>
                  <div class="collapsible-header"><i class="material-icons">pageview</i>
                    <%= t.name %>
                  </div>
                  <div class="collapsible-body red lighten-2 white-text text-darken-2">
                    <p>
                      <%= t.description %>
                    </p>
                    <p>
                      <strong>Prioridade: </strong>
                      <%= t.priority %>
                      <br>
                      <strong>Status: </strong>
                      <%= t.stage.name %>
                      <!-- Modal Trigger -->
                        <a class="waves-effect waves-light btn-floating modal-trigger blue right" href="#modal-task-<%=t.id%>">
                          <i class="tiny material-icons">mode_edit</i>
                        </a>
                        <%= link_to task_path(id: t.id, command: 'deactivate'), data: { confirm: 'Tem certeza que deseja arquivar esta tarefa?' }, class: 'waves-effect waves-light btn-floating modal-trigger red right' do %>
                          <i class="material-icons">archive</i>
                        <% end %>
                    </p>
                    <!-- Modal Structure -->
                    <% @task = t %>
                    <div id="modal-task-<%=t.id%>" class="modal black-text">
                      <div class="modal-content">
                        <h4>Editar tarefa: <%= t.name %> </h4>
                        <%= render 'tasks/form' %>
                      </div>
                    </div>
                    <!-- End Modal -->
                    <br>
                  </div>
                </li>
            <% end %>
          </ul>
        <div class="card-action center">
            <!-- Modal Trigger -->
              <a class="waves-effect waves-light btn-floating modal-trigger green" href="#modal-task-new-<%= s.id %>">
                <i class="tiny material-icons">playlist_add</i>
              </a>
            </p>
            <!-- Modal Structure -->
            <% @task = Task.new %>
            <% @task.stage_id = s.id %>
            <% @task.project_id = @project.id %>
            <div id="modal-task-new-<%= s.id %>" class="modal black-text">
              <div class="modal-content">
                <h4>Criar tarefa</h4>
                <%= render 'tasks/form' %>
              </div>
            </div>
            <!-- End Modal -->
        </div>
      </div>
    </div>
  <% end %>
  <div class="col right">
    <div class="row">
      <%= link_to projects_tasks_archive_path(project_id: @project.id), class: 'btn-floating btn-large waves-effect waves-light grey right' do %>
        <i class="material-icons">list</i>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="left col">
    <%= link_to 'Voltar', projects_path, class: 'waves-effect waves-light btn' %>
  </div>
  <div class="col">
    <%= link_to 'Editar projeto', edit_project_path(@project), class: 'waves-effect blue waves-light btn'%>
  </div>
</div>

app/views/projects/tasks_archive.html.erb
<h4 class="center-align">Tarefas arquivadas</h4>

<ul class="collection">
  <% @tasks.each do |t| %>
    <li class="collection-item">
      <%= link_to task_path(id: t.id, command: 'activate'), data: { confirm: 'Tem certeza que deseja re-ativar esta tarefa?' } do %>
        <i class="material-icons right">unarchive</i>
      <% end %>
      <span class="title"><%= t.name %></span>
      <p><%= t.description %><br>
      </p>
    </li>
  <% end %>
</ul>
<div class="row">
  <div class="left col">
    <%= link_to 'Voltar', project_path(@project), class: 'waves-effect waves-light btn' %>
  </div>
</div>