config/routes.rb
Rails.application.routes.draw do
  resources :stages
  resources :tasks
  resources :roles
  resources :systems
  devise_for :users
  get 'projects/tasks_archive' => 'projects#tasks_archive'
  get 'projects/archive' => 'projects#archive'
  resources :projects

  root 'projects#index'

end

app/models/stage.rb
class Stage < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :project
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
    @stage.project_id = params[:project_id]
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage.project, notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage.project, notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    back = @stage.project
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to back, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:name, :project_id)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_for(@stage) do |f| %>
  <% if @stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% @stage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<h1>Listing Stages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.name %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form' %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @stage.name %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>