config/routes.rb
Rails.application.routes.draw do
  resources :stages
  resources :tasks
  resources :roles
  resources :systems
  devise_for :users
  get 'projects/tasks_archive' => 'projects#tasks_archive'
  get 'projects/archive' => 'projects#archive'
  resources :projects

  root 'projects#index'

end

app/models/system.rb
class System < ActiveRecord::Base
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :set_system, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:some_action_without_auth]

  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system
      @system = System.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_params
      params[:system]
    end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_form.html.erb
<%= form_for(@system) do |f| %>
  <% if @system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% @system.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/systems/new.html.erb
<h1>New System</h1>

<%= render 'form' %>

<%= link_to 'Voltar', systems_path %>

app/views/systems/show.html.erb
<%= link_to 'Edit', edit_system_path(@system) %> |
<%= link_to 'Voltar', systems_path %>